### ISSUE TITLE
Management: Produce a doc describing the project with reference to component

### ISSUE THREAD

**Issue by inidaname** [mainheartng/organization#14]
Produce a document describing the project and it component for the team overview of what they are working. The file should include the following

- [x] Name of the project
- [x] Short Description of the project
- [ ] User target
- [ ] Indicate if user research has been conducted
- [ ] Provide examples of similar project in the market

**Comment by inidaname** [comment]
This is available https://github.com/mainheartng/projects-briefs
